require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectMembershipsController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectMembership. As you add validations to ProjectMembership, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all project_memberships as @project_memberships" do
      project_membership = ProjectMembership.create! valid_attributes
      get :index
      assigns(:project_memberships).should eq([project_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested project_membership as @project_membership" do
      project_membership = ProjectMembership.create! valid_attributes
      get :show, :id => project_membership.id.to_s
      assigns(:project_membership).should eq(project_membership)
    end
  end

  describe "GET new" do
    it "assigns a new project_membership as @project_membership" do
      get :new
      assigns(:project_membership).should be_a_new(ProjectMembership)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_membership as @project_membership" do
      project_membership = ProjectMembership.create! valid_attributes
      get :edit, :id => project_membership.id.to_s
      assigns(:project_membership).should eq(project_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectMembership" do
        expect {
          post :create, :project_membership => valid_attributes
        }.to change(ProjectMembership, :count).by(1)
      end

      it "assigns a newly created project_membership as @project_membership" do
        post :create, :project_membership => valid_attributes
        assigns(:project_membership).should be_a(ProjectMembership)
        assigns(:project_membership).should be_persisted
      end

      it "redirects to the created project_membership" do
        post :create, :project_membership => valid_attributes
        response.should redirect_to(ProjectMembership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_membership as @project_membership" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectMembership.any_instance.stub(:save).and_return(false)
        post :create, :project_membership => {}
        assigns(:project_membership).should be_a_new(ProjectMembership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectMembership.any_instance.stub(:save).and_return(false)
        post :create, :project_membership => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_membership" do
        project_membership = ProjectMembership.create! valid_attributes
        # Assuming there are no other project_memberships in the database, this
        # specifies that the ProjectMembership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectMembership.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => project_membership.id, :project_membership => {'these' => 'params'}
      end

      it "assigns the requested project_membership as @project_membership" do
        project_membership = ProjectMembership.create! valid_attributes
        put :update, :id => project_membership.id, :project_membership => valid_attributes
        assigns(:project_membership).should eq(project_membership)
      end

      it "redirects to the project_membership" do
        project_membership = ProjectMembership.create! valid_attributes
        put :update, :id => project_membership.id, :project_membership => valid_attributes
        response.should redirect_to(project_membership)
      end
    end

    describe "with invalid params" do
      it "assigns the project_membership as @project_membership" do
        project_membership = ProjectMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectMembership.any_instance.stub(:save).and_return(false)
        put :update, :id => project_membership.id.to_s, :project_membership => {}
        assigns(:project_membership).should eq(project_membership)
      end

      it "re-renders the 'edit' template" do
        project_membership = ProjectMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectMembership.any_instance.stub(:save).and_return(false)
        put :update, :id => project_membership.id.to_s, :project_membership => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_membership" do
      project_membership = ProjectMembership.create! valid_attributes
      expect {
        delete :destroy, :id => project_membership.id.to_s
      }.to change(ProjectMembership, :count).by(-1)
    end

    it "redirects to the project_memberships list" do
      project_membership = ProjectMembership.create! valid_attributes
      delete :destroy, :id => project_membership.id.to_s
      response.should redirect_to(project_memberships_url)
    end
  end

end
