require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudySessionsController do

  # This should return the minimal set of attributes required to create a valid
  # StudySession. As you add validations to StudySession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all study_sessions as @study_sessions" do
      study_session = StudySession.create! valid_attributes
      get :index
      assigns(:study_sessions).should eq([study_session])
    end
  end

  describe "GET show" do
    it "assigns the requested study_session as @study_session" do
      study_session = StudySession.create! valid_attributes
      get :show, :id => study_session.id.to_s
      assigns(:study_session).should eq(study_session)
    end
  end

  describe "GET new" do
    it "assigns a new study_session as @study_session" do
      get :new
      assigns(:study_session).should be_a_new(StudySession)
    end
  end

  describe "GET edit" do
    it "assigns the requested study_session as @study_session" do
      study_session = StudySession.create! valid_attributes
      get :edit, :id => study_session.id.to_s
      assigns(:study_session).should eq(study_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudySession" do
        expect {
          post :create, :study_session => valid_attributes
        }.to change(StudySession, :count).by(1)
      end

      it "assigns a newly created study_session as @study_session" do
        post :create, :study_session => valid_attributes
        assigns(:study_session).should be_a(StudySession)
        assigns(:study_session).should be_persisted
      end

      it "redirects to the created study_session" do
        post :create, :study_session => valid_attributes
        response.should redirect_to(StudySession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved study_session as @study_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudySession.any_instance.stub(:save).and_return(false)
        post :create, :study_session => {}
        assigns(:study_session).should be_a_new(StudySession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudySession.any_instance.stub(:save).and_return(false)
        post :create, :study_session => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested study_session" do
        study_session = StudySession.create! valid_attributes
        # Assuming there are no other study_sessions in the database, this
        # specifies that the StudySession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StudySession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => study_session.id, :study_session => {'these' => 'params'}
      end

      it "assigns the requested study_session as @study_session" do
        study_session = StudySession.create! valid_attributes
        put :update, :id => study_session.id, :study_session => valid_attributes
        assigns(:study_session).should eq(study_session)
      end

      it "redirects to the study_session" do
        study_session = StudySession.create! valid_attributes
        put :update, :id => study_session.id, :study_session => valid_attributes
        response.should redirect_to(study_session)
      end
    end

    describe "with invalid params" do
      it "assigns the study_session as @study_session" do
        study_session = StudySession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudySession.any_instance.stub(:save).and_return(false)
        put :update, :id => study_session.id.to_s, :study_session => {}
        assigns(:study_session).should eq(study_session)
      end

      it "re-renders the 'edit' template" do
        study_session = StudySession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudySession.any_instance.stub(:save).and_return(false)
        put :update, :id => study_session.id.to_s, :study_session => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested study_session" do
      study_session = StudySession.create! valid_attributes
      expect {
        delete :destroy, :id => study_session.id.to_s
      }.to change(StudySession, :count).by(-1)
    end

    it "redirects to the study_sessions list" do
      study_session = StudySession.create! valid_attributes
      delete :destroy, :id => study_session.id.to_s
      response.should redirect_to(study_sessions_url)
    end
  end

end
